CREATE TABLE ALUNOS(
  RA NUMBER(10),
  NOME VARCHAR(100) NOT NULL,
  ENDERECO VARCHAR(100) NOT NULL,
  CIDADE VARCHAR(100) NOT NULL,
  CONSTRAINT ALU_PK PRIMARY KEY (RA)
);

CREATE TABLE DISCIPLINAS(
  COD_DISC NUMBER(10),
  NOME_DISC VARCHAR(50) NOT NULL,
  CARGA_HOR VARCHAR(50) NOT NULL,
  CONSTRAINT DIS_PK PRIMARY KEY (COD_DISC)
);

CREATE TABLE PROFESSORES(
  COD_PROF NUMBER(10),
  NOME VARCHAR(100) NOT NULL,
  ENDERECO VARCHAR(100) NOT NULL,
  CIDADE VARCHAR(100) NOT NULL,
  CONSTRAINT PRO_PK PRIMARY KEY (COD_PROF)
);

CREATE TABLE TURMA(
  COD_TURMA NUMBER(10),
  COD_DISC NUMBER(10) NOT NULL,
  COD_PROF NUMBER(10) NOT NULL,
  ANO NUMBER(4) NOT NULL,
  HORARIO NUMBER(5) NOT NULL,
  CONSTRAINT TUR_PK PRIMARY KEY (COD_TURMA),
  CONSTRAINT PRO_TURMA_FK FOREIGN KEY (COD_PROF) REFERENCES PROFESSORES(COD_PROF),
  CONSTRAINT DIS_TURMA_FK FOREIGN KEY (COD_DISC) REFERENCES DISCIPLINAS(COD_DISC)
);

CREATE TABLE HISTORICO(
  RA NUMBER(10) NOT NULL,
  COD_DISC NUMBER(10) NOT NULL,
  COD_TURMA NUMBER(10) NOT NULL, 
  COD_PROF NUMBER(10) NOT NULL,
  ANO NUMBER(4) NOT NULL,
  FREQUENCIA NUMBER(3) NOT NULL,
  NOTA NUMBER(2) NOT NULL,
  CONSTRAINT HIS_PK PRIMARY KEY (RA),
  CONSTRAINT ALU_HIS_FK FOREIGN KEY (RA) REFERENCES ALUNOS(RA),
  CONSTRAINT DIS_HIS_FK FOREIGN KEY (COD_DISC) REFERENCES DISCIPLINAS(COD_DISC),
  CONSTRAINT TUR_HIS_FK FOREIGN KEY (COD_TURMA) REFERENCES TURMA(COD_TURMA),
  CONSTRAINT PRO_HIS_FK FOREIGN KEY (COD_PROF) REFERENCES PROFESSORES(COD_PROF)
);
 
